/**
 * Platform detection.
 *
 * The Android wrapper is a TWA (Trusted Web Activity) generated by PWABuilder
 * that loads the same Vercel-served web app at app.moodkinstudio.com. There
 * is no separate Android build, so we cannot use a build-time env var to tag
 * the bundle — detection must happen at runtime.
 *
 * Subscription flow has to branch on whether we're inside the Play Store
 * wrapper, because Play Store policy forbids Stripe for in-app subscriptions.
 *
 * Detection signals, in order of trust:
 *  1. sessionStorage 'moodkin_platform=android'  — set on first load when
 *     start_url carries ?platform=android. The TWA manifest's start_url
 *     must include this query string (see android-signing/Readme-build.md).
 *     This is the canonical signal for the rest of the session.
 *  2. document.referrer starts with "android-app://"  — Chrome sets this
 *     when the page is launched from a TWA. Reliable per Chromium docs,
 *     but can be missing on certain cold-launch paths, which is why we
 *     prefer signal 1.
 *  3. Display-mode standalone + Android UA + Digital Goods API present —
 *     last-ditch heuristic for older Chrome / sideloaded builds.
 *
 * A user who installed the PWA from Chrome on Android will hit signal 3
 * but NOT have the Digital Goods API, so we'll still route them to Stripe.
 */

export type Platform = 'web' | 'android-app'

const SESSION_KEY = 'moodkin_platform'
const QUERY_PARAM = 'platform'

/**
 * Read ?platform=android from the current URL (set by the TWA start_url)
 * and persist it for the rest of the session. Safe to call multiple times —
 * subsequent calls are no-ops. Call once at app boot, before detectPlatform.
 */
export function captureStartupPlatform(): void {
  if (typeof window === 'undefined') return
  try {
    const fromQuery = new URLSearchParams(window.location.search).get(QUERY_PARAM)
    if (fromQuery === 'android') {
      sessionStorage.setItem(SESSION_KEY, 'android')
    }
  } catch {
    // sessionStorage can throw in privacy modes — silently fall back to other signals.
  }
}

export function detectPlatform(): Platform {
  if (typeof window === 'undefined') return 'web'

  // Signal 1: stashed value from start_url ?platform=android
  try {
    if (sessionStorage.getItem(SESSION_KEY) === 'android') return 'android-app'
  } catch {
    // ignore — fall through to other signals
  }

  // Re-check the live URL in case captureStartupPlatform hasn't run yet
  // (e.g. detectPlatform called during first render).
  try {
    if (new URLSearchParams(window.location.search).get(QUERY_PARAM) === 'android') {
      return 'android-app'
    }
  } catch {
    // ignore
  }

  // Signal 2: TWA referrer
  if (typeof document !== 'undefined' && document.referrer.startsWith('android-app://')) {
    return 'android-app'
  }

  // Signal 3: standalone + Android UA + Digital Goods API
  const isStandalone = window.matchMedia?.('(display-mode: standalone)').matches ?? false
  const isAndroidUA = /Android/.test(navigator.userAgent)
  const hasDigitalGoods = 'getDigitalGoodsService' in window
  if (isStandalone && isAndroidUA && hasDigitalGoods) return 'android-app'

  return 'web'
}

export function isAndroidApp(): boolean {
  return detectPlatform() === 'android-app'
}

/**
 * Header the client sends on subscription-related requests so the server
 * can record which platform a purchase originated from. The server does
 * NOT trust this for entitlement decisions — entitlement is decided by
 * whatever Stripe / Play Developer API tells us — but it's useful for
 * routing and for the subscription_source column.
 */
export const PLATFORM_HEADER = 'x-moodkin-platform'
